### ISSUE TITLE
undefined method `spree_user_omniauth_authorize_url'

### ISSUE THREAD

**Issue by aldavid** [solidusio-contrib/solidus_social#16]
Hi,

I'm building an online shop with solidus and I've integrated it with solidus-social.
It worked properly for 1 month or so, but for the last 2-3 weeks it doesn't. The status in GIT shows failed, as well.

This is the error I'm getting when I try to go into Account page:

Showing /usr/local/rvm/gems/ruby-2.2.3/gems/solidus_social-1.0.0/app/views/spree/shared/_social.html.erb where line #8 raised:

undefined method `spree_user_omniauth_authorize_url' for #ActionDispatch::Routing::RoutesProxy:0x0000000b9599c0
Extracted source (around line #37):

```
      send(method, *args)
    else
      super
    end
  end
end
```

Thanks,
Alex

**Comment by aldavid** [comment]
It seems that the issue is related to solidus_auth_devise 1.5.0
I've downgraded to 1.4.0 and everything seems ok.

I'm taking a look as well over the changes and I'll keep you updated.

Thanks,
Alex

**Comment by jarednorman** [comment]
Thanks for the bug report. I've also looked into this, but I haven't tracked down the actual root of the problem yet. Let me know if you find anything.

**Comment by jhawthorn** [comment]
@aldavid thanks for the report. This should be fixed in solidus_social master
