### ISSUE TITLE
spree_authentication_methods tables has api_secret and api_key but they seem unused

### ISSUE THREAD

**Issue by spaghetticode** [solidusio-contrib/solidus_social#26]
It seems that the key/secret configuration is handled only via ENV variables loaded by the `solidus_social.rb` initializer. But there are those 2 columns in the `spree_authentication_methods` table, which seem to be not used (anymore?). Those columns appear also on the admin authentication list, and they're never populated. This is a bit confusing

**Comment by mamhoff** [comment]
@spaghetticode good find. When I introduced the secret configuration via ENV vars, I did not want to go and delete the table. But really, the entire table is not necessary. If you want to, you can add a PR to entire remove the table.

**Comment by jarednorman** [comment]
I can fix that during the SoldiusConf hack days.
