### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by htorohn** [solidusio-contrib/solidus_social#27]
Hello,

i'm new with Ruby on Rails and i'm trying to install this extension but i get the following error

$ bundle exec rails g solidus_social:install
/Users/hectortoro/Documents/Desarrollo/solidus/config/application.rb:4:in `require': cannot load such file -- neo4j/railtie (LoadError)
	from /Users/hectortoro/Documents/Desarrollo/solidus/config/application.rb:4:in `<top (required)>'

any thought on what could be the problem

**Comment by jarednorman** [comment]
Sorry, but this error doesn't look like it has anything to do with `solidus_social`. It happening inside your application code (`config/application.rb`), and refers to a gem (`neo4j`) that has nothing to do with `solidus_social`.
