### ISSUE TITLE
Error in 'omniauth_callbacks_controlle'

### ISSUE THREAD

**Issue by sechix** [solidusio-contrib/solidus_social#28]
I get this error with last master version with solidus 2.2:

/app/vendor/bundle/ruby/2.3.0/bundler/gems/solidus_social-37cd5335f76b/app/controllers/spree/omniauth_callbacks_controller.rb:15:in `<class:OmniauthCallbacksController>': undefined method `keys' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/solidus_social-37cd5335f76b/app/controllers/spree/omniauth_callbacks_controller.rb:1:in `<top (required)>'

**Comment by jarednorman** [comment]
My guess is you missed the install step (`bundle && bundle exec rails g solidus_social:install`) which should have installed the initializer that configures soldius_social when the app starts up, or you're upgrading from an older version which didn't have this.

Either way, you need to add [this initializer](https://github.com/solidusio-contrib/solidus_social/blob/master/lib/generators/solidus_social/install/templates/config/initializers/solidus_social.rb) to your application.
