### ISSUE TITLE
View partial _configuration_menu overrides solidus file

### ISSUE THREAD

**Issue by spaghetticode** [solidusio-contrib/solidus_social#30]
The view partial file  `app/views/spree/admin/shared/_configuration_menu.html.erb` overrides the original solidus partial files, which causes other plugins depending on the `admin_configurations_sidebar_menu` hook to fail. 

In short, you won't see other plugins tabs/enhanchements if you use `solidus_social`.

**Comment by jarednorman** [comment]
Upcoming PR that fully removes the `AuthenticationMethod` model will fix this.

**Comment by spaghetticode** [comment]
@jarednorman Alright, meanwhile I have already proposed a PR for this, I needed to address the issue ASAP. I thought the file could be safely removed. See PR https://github.com/solidusio-contrib/solidus_social/pull/31
