### ISSUE TITLE
solidus_social:install results in `method_missing': undefined method `add_routes' for Spree::Core::Engine:Class (NoMethodError)

### ISSUE THREAD

**Issue by sandfront** [solidusio-contrib/solidus_social#37]
Hi there! I'm having this issue when running `bundle exec rails g solidus_social:installsolidus_social:install`

**Comment by jhawthorn** [comment]
Hi @therealaung. Thanks for the report.

I believe this was fixed in #21, but we hadn't released a new gem in a while.

I've just cut [version 1.2.0](https://rubygems.org/gems/solidus_social/versions/1.2.0) which should fix this issue.
