### ISSUE TITLE
Translation missing because scoped weirdly: en.authentications.spree.destroy

### ISSUE THREAD

**Issue by jgujgu** [solidusio-contrib/solidus_social#50]
This is not a huge problem obviously, but the translation path for "destroy" ends up being slightly wrong, displaying this on the frontend:
```
translation missing: en.authentications.spree.destroy
```
I don't know how to scope it correctly but here it is in the controller:
https://github.com/solidusio-contrib/solidus_social/blob/master/app/controllers/spree/user_authentications_controller.rb#L9

**Comment by jarednorman** [comment]
Thanks for the report! I'll look into it.
