### ISSUE TITLE
Names Pulled From Facebook

### ISSUE THREAD

**Issue by braidn** [solidusio-contrib/solidus_social#6]
Hey All,

With a show of thumbs up reactions in this issue, who would love to see the app assign the user's firstname and lastname if they were settable on the Store's user object? Just spit balling a small feature.

**Comment by jarednorman** [comment]
Seems like a decent feature, though I'm not sure about what the best way to implement that would be as the only place names are currently stored is on addresses. Perhaps it might be desirable to add a hook so that developers could grab that info and store it where ever made sense in their schema?

**Comment by cbrunsdon** [comment]
For the record I've always though user should support first/last names. Only being on addresses drives me nuts.

**Comment by mamhoff** [comment]
Go for it. I personally believe first and last names are wrong in many ways (People have a name, and that's it, really), but I do understand there's a lot of use for this. :+1:

**Comment by Sinetheta** [comment]
http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

**Comment by braidn** [comment]
Thank you all for the great feedback. I feel much like Clarke in this regard, the lack of a name of any kind (first,last,singular) on user drives me nuts. I will implement it so that if your User responds to first_name/firstname or last_name/lastname then we will save the returned info to that user.

**Comment by zhuwu** [comment]
This is my current workaround:
1. Add the following in an initializer:
   
   ```
   class SolidusSocialConfig < Rails::Application
   config.after_initialize do
     Devise.omniauth_configs[:facebook]&.strategy&.merge!({ scope: 'email', info_fields: 'email,name,first_name,last_name' })
   end
   end
   ```
   
   Then, `omniauth-facebook` will request for `first_name` and `last_name` and you can get them in `auth_hash`.
2. Override method `omniauth_callback` in `Spree::OmniauthCallbacksController` to include your own logic.
