### ISSUE TITLE
Facebook login not working for me

### ISSUE THREAD

**Issue by abhayathapa** [solidusio-contrib/solidus_social#97]
Hi can you provide details on Facebook login. I dont know what im missing.

I get this error `This redirect failed because the redirect URI is not white-listed in the app's client OAuth settings. Make sure that the client and web OAuth logins are on and add all your app domains as valid OAuth redirect URIs.`

The url i used is `<%= link_to "Login with FB", "/users/auth/facebook" %>`

I have added  facebook  keys on solidus_social.rb
api_key: 342367450747827,
api_secret....

Am i Missing something. I tried with ngrok and localhost both for development  on the facebook app but failed in both

**Comment by kennyadsl** [comment]
Hey there, sorry for the long wait. Is this still an issue? Going to close since it doesn't seem related to the extension but feel free to answer and re-open.
